-- lottery.draw_statuses определение

-- Drop table

-- DROP TABLE lottery.draw_statuses;
CREATE SCHEMA IF NOT EXISTS lottery;

CREATE TABLE lottery.draw_statuses (
  id int4 NOT NULL,
  "name" varchar NOT NULL, -- Название статуса
  CONSTRAINT draw_statuses_name UNIQUE (name),
  CONSTRAINT draw_statuses_pk PRIMARY KEY (id)
);

-- Column comments

COMMENT ON COLUMN lottery.draw_statuses."name" IS 'Название статуса';


-- lottery.draws определение

-- Drop table

-- DROP TABLE lottery.draws;

CREATE TABLE lottery.draws (
  id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
  status_id int4 NOT NULL, -- Идентификатор статуса
  lottery_type varchar NOT NULL, -- Тип лотереи
  sale_date timestamp NOT NULL, -- Дата начала продаж
  start_date timestamp NOT NULL, -- Дата розыгрыша
  "cost" float4 DEFAULT 0 NOT NULL, -- Стоимость билета в тираже
  CONSTRAINT draws_pk PRIMARY KEY (id)
);

-- Column comments

COMMENT ON COLUMN lottery.draws.status_id IS 'Идентификатор статуса';
COMMENT ON COLUMN lottery.draws.lottery_type IS 'Тип лотереи';
COMMENT ON COLUMN lottery.draws.sale_date IS 'Дата начала продаж';
COMMENT ON COLUMN lottery.draws.start_date IS 'Дата розыгрыша';
COMMENT ON COLUMN lottery.draws."cost" IS 'Стоимость билета в тираже';


-- lottery.invoices определение

-- Drop table

-- DROP TABLE lottery.invoices;

CREATE TABLE lottery.invoices (
  id serial4 NOT NULL,
  user_id int4 NULL,
  ticket_id int4 NULL,
  status_id int4 NULL,
  date_invoice timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
  price float4 NULL,
  status_change timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
  CONSTRAINT invoices_pkey PRIMARY KEY (id)
);


-- lottery.ticket_statuses определение

-- Drop table

-- DROP TABLE lottery.ticket_statuses;

CREATE TABLE lottery.ticket_statuses (
  id int4 NOT NULL,
  "name" varchar NOT NULL, -- Название статуса
  CONSTRAINT ticket_statuses_name UNIQUE (name),
  CONSTRAINT ticket_statuses_pk PRIMARY KEY (id)
);

-- Column comments

COMMENT ON COLUMN lottery.ticket_statuses."name" IS 'Название статуса';


-- lottery.tickets определение

-- Drop table

-- DROP TABLE lottery.tickets;

CREATE TABLE lottery.tickets (
  id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
  status_id int4 NOT NULL, -- Статус билета
  draw_id int4 NOT NULL, -- Тираж билета
  "data" varchar NOT NULL, -- Данные билета
  user_id int4 NULL, -- Владелец билета
  lock_time timestamp NULL,
  CONSTRAINT tickets_pk PRIMARY KEY (id)
);

-- Column comments

COMMENT ON COLUMN lottery.tickets.status_id IS 'Статус билета';
COMMENT ON COLUMN lottery.tickets.draw_id IS 'Тираж билета';
COMMENT ON COLUMN lottery.tickets."data" IS 'Данные билета';
COMMENT ON COLUMN lottery.tickets.user_id IS 'Владелец билета';


-- lottery.users определение

-- Drop table

-- DROP TABLE lottery.users;

CREATE TABLE lottery.users (
  id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
  "name" varchar NOT NULL,
  username varchar NOT NULL,
  "password" varchar NOT NULL,
  email varchar DEFAULT false NOT NULL,
  "admin" bool NOT NULL,
  CONSTRAINT users_email UNIQUE (email),
  CONSTRAINT users_pk PRIMARY KEY (id),
  CONSTRAINT users_username UNIQUE (username)
);


-- lottery.draw_results определение

-- Drop table

-- DROP TABLE lottery.draw_results;

CREATE TABLE lottery.draw_results (
  id serial4 NOT NULL,
  draw_id int4 NOT NULL,
  win_combination _int4 NOT NULL,
  result_time timestamp DEFAULT now() NOT NULL,
  CONSTRAINT draw_results_pkey PRIMARY KEY (id),
  CONSTRAINT draw_results_draw_id_fkey FOREIGN KEY (draw_id) REFERENCES lottery.draws(id)
);
