CREATE TABLE draws
(
    id           int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_id    int4                                  NOT NULL, -- Идентификатор статуса
    lottery_type varchar                               NOT NULL, -- Тип лотереи
    sale_date    timestamp                             NOT NULL, -- Дата начала продаж
    start_date   timestamp                             NOT NULL, -- Дата розыгрыша
    "cost"       float4 DEFAULT 0                      NOT NULL, -- Стоимость билета в тираже
    CONSTRAINT draws_pk PRIMARY KEY (id)
);

CREATE TABLE draw_statuses
(
    id     int4    NOT NULL,
    "name" varchar NOT NULL, -- Название статуса
    CONSTRAINT draw_statuses_name UNIQUE (name),
    CONSTRAINT draw_statuses_pk PRIMARY KEY (id)
);

INSERT INTO draw_statuses (id, "name")
VALUES (0, 'Неизвестно'),
       (1, 'Запланирован'),
       (2, 'Активен'),
       (3, 'Завершён'),
       (4, 'Отменён'),
       (5, 'Испорчен');
