CREATE TABLE tickets
(
    id        int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_id int4                                  NOT NULL, -- Статус билета
    draw_id   int4                                  NOT NULL, -- Тираж билета
    "data"    varchar                               NOT NULL, -- Данные билета
    cost      float4                                NOT NULL, -- Стоимость билета
    user_id   int4 NULL,                                      -- Владелец билета
    lock_time timestamp NULL,
    CONSTRAINT tickets_pk PRIMARY KEY (id)
);

CREATE TABLE ticket_statuses
(
    id     int4    NOT NULL,
    "name" varchar NOT NULL, -- Название статуса
    CONSTRAINT ticket_statuses_name UNIQUE (name),
    CONSTRAINT ticket_statuses_pk PRIMARY KEY (id)
);

CREATE INDEX idx_tickets_draw_id ON tickets (draw_id);
CREATE INDEX idx_tickets_user_id ON tickets (user_id);

INSERT INTO ticket_statuses (id, "name")
VALUES (0, 'Неизвестно'),
       (1, 'Готов'),
       (2, 'Куплен'),
       (3, 'Выиграл'),
       (4, 'Проиграл');
