CREATE
EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users
(
    id         int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name"     varchar                               NOT NULL,
    username   varchar                               NOT NULL,
    "password" varchar                               NOT NULL,
    email      varchar DEFAULT false                 NOT NULL,
    "admin"    bool                                  NOT NULL,
    wallet     float4  DEFAULT 0 NULL,
    CONSTRAINT users_email UNIQUE (email),
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT users_username UNIQUE (username)
);
