name: Go build and test

on:
  push:
    branches:
    - dev
    - main
  pull_request:
    branches:
    - dev
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install linters
        run: go install golang.org/x/lint/golint@latest

      - name: Lint
        run: golint ./...

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...
